### ISSUE TITLE
ccache fails compiling Linux kernel

### ISSUE THREAD

**Issue by spstarr** [ccache/ccache#153]
ccache version 3.3.3
ccache-3.3.3-1.fc25.x86_64

/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/.fixdep.o.cmd:3: *** empty variable name.  Stop.
Makefile:42: recipe for target '/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/fixdep-in.o' failed
make[6]: *** [/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/fixdep-in.o] Error 2
/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/build/Makefile.include:4: recipe for target 'fixdep' failed
make[5]: *** [fixdep] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/help.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/elf.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/pager.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/parse-options.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/special.o
  LD       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/arch/x86/objtool-in.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/run-command.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/sigchain.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/subcmd-config.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/objtool.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/libstring.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/str_error_r.o
  LD       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/objtool-in.o
  HOSTCC  arch/x86/tools/relocs_32.o
  LD       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/libsubcmd-in.o
Makefile:59: recipe for target '/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/libsubcmd.a' failed
make[4]: *** [/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/libsubcmd.a] Error 2
Makefile:61: recipe for target 'objtool' failed
make[3]: *** [objtool] Error 2
Makefile:1613: recipe for target 'tools/objtool' failed
make[2]: *** [tools/objtool] Error 2
make[2]: *** Waiting for unfinished jobs....
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  arch/x86/tools/relocs
make[2]: *** wait: No child processes.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.DenykN (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.DenykN (%build)
scripts/package/Makefile:50: recipe for target 'rpm' failed
make[1]: *** [rpm] Error 1
Makefile:1331: recipe for target 'rpm' failed
make: *** [rpm] Error 2

We had something like this before... regression from #133

**Comment by jrosdahl** [comment]
> We had something like this before... regression from #133

It's highly unlikely that this is a regression in 3.3.3. The [changes between 3.3.2 (where #133 was fixed) and 3.3.3](https://github.com/ccache/ccache/compare/v3.3.2...v3.3.3) are very few and don't affect any code path related to dependency files.

Could it be that you have bad results from ccache 3.3.1 in the cache? Please try clearing the cache. If that doesn't help, it's the fix in 3.3.2 that doesn't work.

**Comment by jrosdahl** [comment]
I have now been able to find some time to try to reproduce this issue but I have not yet succeeded.

My attempted reproduction recipe looks like this:

```
ccache -zC
git clean -fxd
make O=build allyesconfig
make O=build tools/objtool
make O=build clean
make O=build tools/objtool
```

I have run the above with ccache 3.3.3 on the following Linux commits without any issues:

* `bd5dbcb4be37ce97b115bf9e8d48ae75f0d8a9a2`
* `a121103c922847ba5010819a3f250f1f7fc84ab8` (AKA `v4.10-rc3` as I guess from your log you were building something similar)
* `49e555a932de57611eb27edf2d1ad03d9a267bdd`

@spstarr: Can you provide a way of reproducing the issue?

**Comment by spstarr** [comment]
I nuked my local .ccache same result:

I use 'make rpm' to build the kernel from kernel.org directly (with git branches)

`[spstarr@segfault linux]$ make rpm
  CHK     include/config/kernel.release
make clean
/bin/sh ./scripts/package/mkspec >./kernel.spec
  TAR     kernel-4.10.0_rc6+.tar.gz
/bin/sh ./scripts/mkversion > ./.tmp_version
mv -f ./.tmp_version ./.version
rpmbuild  --target x86_64 -ta kernel-4.10.0_rc6+.tar.gz
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.bBUvO9
+ umask 022
+ cd /home/spstarr/rpmbuild/BUILD
+ cd /home/spstarr/rpmbuild/BUILD
+ rm -rf kernel-4.10.0_rc6+
+ /usr/bin/gzip -dc /home/spstarr/Sources/linux/kernel-4.10.0_rc6+.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd kernel-4.10.0_rc6+
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.gJq7mI
+ umask 022
+ cd /home/spstarr/rpmbuild/BUILD
+ cd kernel-4.10.0_rc6+
+ make clean
+ make -j8
  CHK     include/config/kernel.release
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h
  HOSTCC  scripts/basic/fixdep
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_64.h
  HYPERCALLS arch/x86/entry/syscalls/../../include/generated/asm/xen-hypercalls.h
  WRAP    arch/x86/include/generated/asm/clkdev.h
  WRAP    arch/x86/include/generated/asm/cputime.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/dma-contiguous.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/mm-arch-hooks.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h
  DESCEND  objtool
  HOSTCC   /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/fixdep.o
  HOSTCC  scripts/basic/bin2c
  HOSTLD   /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/fixdep-in.o
  LINK     /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/fixdep
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/arch/x86/decode.o
/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/.fixdep.o.cmd:3: *** empty variable name.  Stop.
Makefile:42: recipe for target '/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/fixdep-in.o' failed
make[6]: *** [/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/fixdep-in.o] Error 2
/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/build/Makefile.include:4: recipe for target 'fixdep' failed
make[5]: *** [fixdep] Error 2
Makefile:59: recipe for target '/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/libsubcmd.a' failed
make[4]: *** [/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/libsubcmd.a] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/builtin-check.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/elf.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/special.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/objtool.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/libstring.o
  LD       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/arch/x86/objtool-in.o
  CC       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/str_error_r.o
  LD       /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/objtool-in.o
Makefile:61: recipe for target 'objtool' failed
make[3]: *** [objtool] Error 2
Makefile:1613: recipe for target 'tools/objtool' failed
make[2]: *** [tools/objtool] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.gJq7mI (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.gJq7mI (%build)
scripts/package/Makefile:50: recipe for target 'rpm' failed
make[1]: *** [rpm] Error 1
Makefile:1331: recipe for target 'rpm' failed
make: *** [rpm] Error 2
`

**Comment by jrosdahl** [comment]
> I use 'make rpm' to build the kernel from kernel.org directly (with git branches)

Sorry, I don't understand how to reproduce the problem given this information. Here's what I did:

```
% make rpm
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 1
Makefile:546: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 2
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'. Stop.
```

This is in a clean clone of the linux Git repository.

It would be very helpful if you could describe more details about what you are doing. It's very time-consuming having to guess. :-) Thanks!

**Comment by spstarr** [comment]
The only step you'd be missing is taking your /boot/ kernel config file and copying it to the kernel source directory so in my case:

cp /boot/config-4.10.0-0.rc6.git2.2.fc26.x86_64 <path-to-git-kernel-sources>/.config

Then make rpm may prompt you for any kernel options that are not set (new ones) then will begin building.

**Comment by jrosdahl** [comment]
Yeah, I didn't mention it, but I created a config and built it without any problem (including `tools/objtool`), so I figured I had to do something else as well.

I would love to be able to reproduce this, but I can't, so there has to be something in your environment that is different than mine.

Some questions that come to mind:

* What OS do you run?
* What filesystem do you build on (i.e. /home/spstarr)?
* What does `ccache -p say`?
* What do you mean by "(with git branches)"?
* Do you get the error on the first build after clearing the cache or on a second rebuild?
* Anything else you think is special about your environment?

**Comment by spstarr** [comment]
Fedora 25 x86_64
/home is a LVM with EXT4 options noatime,nodiratime

ccache -p

`(default) base_dir = 
(default) cache_dir = /home/spstarr/.ccache
(default) cache_dir_levels = 2
(default) compiler = 
(default) compiler_check = mtime
(default) compression = false
(default) compression_level = 6
(default) cpp_extension = 
(default) direct_mode = true                                                                                                                                 
(default) disable = false                                                                                                                                    
(default) extra_files_to_hash =                                                                                                                              
(default) hard_link = false                                                                                                                                  
(default) hash_dir = true                                                                                                                                    
(default) ignore_headers_in_manifest =                                                                                                                       
(default) keep_comments_cpp = false                                                                                                                          
(default) limit_multiple = 0.8                                                                                                                               
(default) log_file =                                                                                                                                         
(default) max_files = 0                                                                                                                                      
(/home/spstarr/.ccache/ccache.conf) max_size = 10.0G                                                                                                         
(default) path =                                                                                                                                             
(default) prefix_command = 
(default) prefix_command_cpp = 
(default) read_only = false
(default) read_only_direct = false
(default) recache = false
(default) run_second_cpp = true
(default) sloppiness = 
(default) stats = true
(default) temporary_dir = 
(default) umask = 
(default) unify = false
`

I use the following git repo setup my repo's .git/config file:

`[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[remote "tip"]
        url = https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git
        fetch = +refs/heads/*:refs/remotes/tip/*
[remote "amd-upstream"]
        url = git://people.freedesktop.org/~agd5f/linux
        fetch = +refs/heads/*:refs/remotes/agd5f/*
[remote "airlied"]
        url = git://people.freedesktop.org/~airlied/linux
        fetch = +refs/heads/*:refs/remotes/airlied/*

[branch "drm-next"]
        remote = airlied
        merge = refs/heads/drm-next
[branch "drm-next-4.10-wip"]
        remote = amd-upstream
        merge = refs/heads/drm-next-4.10-wip
`
So I am using Linus kernel.org git but also custom branches based off his code.

I get the error every build, even if i nuke .ccache.

PATH = `/home/spstarr/google-cloud-sdk/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lib64/qt5/bin:/home/spstarr/.local/bin:/home/spstarr/bin
`

I'm not sure what else might break this environment? Any debugging i can turn on with ccache?

**Comment by jrosdahl** [comment]
> I'm not sure what else might break this environment?

I see nothing strange about your setup, unfortunately.

> Any debugging i can turn on with ccache?

Yes, set `CCACHE_LOGFILE` to an absolute path of a log file. It might give some clue, but I doubt it in this particular case, but it's worth trying.

If we don't get closer, perhaps can you could give me access to your machine in some way? Or could you debug ccache yourself? I'm getting desperate now. :-)

**Comment by jrosdahl** [comment]
Also:

* Which exact commit hash of Linux did you build?
* What does /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/.fixdep.o.cmd look like after a failure?
* What does /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/.fixdep.o.cmd look like after building without ccache?

**Comment by spstarr** [comment]
Very weird.. gcc shows 'failure' with ccache, attached log file


[ccache-debug.txt](https://github.com/ccache/ccache/files/768233/ccache-debug.txt)

**Comment by jrosdahl** [comment]
> ccache-debug.txt

Thanks!

> Very weird.. gcc shows 'failure' with ccache, attached log file

I don't see anything unexpected in the log file at a quick glance. What do you think looks weird?

> /home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc6+/tools/objtool/.fixdep.o.cmd - contains text of dependencies.

Yes, but the content has to be a different between the two runs since make says `/home/spstarr/rpmbuild/BUILD/kernel-4.10.0_rc3+/tools/objtool/.fixdep.o.cmd:3: *** empty variable name. Stop.` when parsing the file (i.e., the file is corrupt in some way) . So what I wanted to know is what the difference is between the corrupt and the non-corrupt version - what is the content with and without ccache?

Also:

* Which exact commit hash of Linux did you build?

**Comment by spstarr** [comment]
It doesn't matter which commit hash for me any kernel build fails. I'll get you the .fixdep.o.cmd file for both.

**Comment by rldleblanc** [comment]
I ran into this problem today and it seems that CONFIG_HAVE_STACK_VALIDATION causes the issue for me.

**Comment by jrosdahl** [comment]
@ridleblanc: Perhaps you could help by showing what `tools/objtool/.fixdep.o.cmd` looks like with and without ccache?

**Comment by rldleblanc** [comment]
I did not see the problem on 4.9.0, but when I try to compile 4.10.0, I see the problem.
```bash
$ ccache --version
ccache version 3.2.7
$ grep HAVE_STACK_VAL .config
CONFIG_HAVE_STACK_VALIDATION=y
```

With ccache
----
```bash
$ make clean
$ make -j 32
  HOSTCC  scripts/kconfig/conf.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  DESCEND  objtool
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/pnmtologo
  HOSTCC   /home/rleblanc/linux/tools/objtool/fixdep.o
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/recordmcount
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/sign-file
  SHIPPED scripts/genksyms/parse.tab.c
  HOSTCC  scripts/genksyms/genksyms.o
  SHIPPED scripts/genksyms/keywords.hash.c
  SHIPPED scripts/genksyms/parse.tab.h
  HOSTCC  scripts/extract-cert
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/genksyms/lex.lex.o
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/devicetable-offsets.s
  HOSTCC  scripts/selinux/mdp/mdp
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTLD  scripts/genksyms/genksyms
cc1: error: to generate dependencies you must specify either -M or -MM
mv: cannot stat ‘/home/rleblanc/linux/tools/objtool/.fixdep.o.tmp’: No such file or directory
make[4]: *** [/home/rleblanc/linux/tools/objtool/fixdep.o] Error 1
make[3]: *** [/home/rleblanc/linux/tools/objtool/fixdep-in.o] Error 2
make[2]: *** [fixdep] Error 2
make[1]: *** [objtool] Error 2
make: *** [tools/objtool] Error 2
make: *** Waiting for unfinished jobs....
  GEN     scripts/mod/devicetable-offsets.h
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/sumversion.o
  UPD     include/config/kernel.release
  HOSTLD  scripts/mod/modpost
make: *** wait: No child processes.  Stop.
$ ls -lhA tools/objtool/
total 536K
drwxr-x---. 3 rleblanc rleblanc   17 Dec 14 12:47 arch
-rw-r-----. 1 rleblanc rleblanc 1.4K Dec 14 12:47 arch.h
-rw-r-----. 1 rleblanc rleblanc  410 Dec 14 12:47 Build
-rw-r-----. 1 rleblanc rleblanc  30K Dec 14 12:47 builtin-check.c
-rw-r-----. 1 rleblanc rleblanc  829 Dec 14 12:47 builtin.h
drwxr-x---. 2 rleblanc rleblanc   34 Dec 14 12:47 Documentation
-rw-r-----. 1 rleblanc rleblanc 8.6K Dec 14 12:47 elf.c
-rw-r-----. 1 rleblanc rleblanc 2.3K Dec 14 12:47 elf.h
-rwxrwxr-x. 1 rleblanc rleblanc  14K Feb 23 13:25 fixdep
-rw-r-----. 1 rleblanc rleblanc   43 Dec 14 12:47 .gitignore
-rw-rw-r--. 1 rleblanc rleblanc 2.4K Feb 23 13:27 Makefile
-rwxrwxr-x. 1 rleblanc rleblanc 431K Feb 23 13:25 objtool
-rw-r-----. 1 rleblanc rleblanc 3.0K Dec 14 12:47 objtool.c
-rw-r-----. 1 rleblanc rleblanc 4.6K Dec 14 12:47 special.c
-rw-r-----. 1 rleblanc rleblanc 1.2K Dec 14 12:47 special.h
-rw-r-----. 1 rleblanc rleblanc 1.6K Dec 14 12:47 warn.h
```

There is no .fixdep.o.cmd file generated

Without ccache
----
```bash
$ ls -lhA tools/objtool/
total 3.6M
drwxr-x---. 3 rleblanc rleblanc   17 Dec 14 12:47 arch
-rw-r-----. 1 rleblanc rleblanc 1.4K Dec 14 12:47 arch.h
-rw-r-----. 1 rleblanc rleblanc  410 Dec 14 12:47 Build
-rw-r-----. 1 rleblanc rleblanc  30K Dec 14 12:47 builtin-check.c
-rw-rw-r--. 1 rleblanc rleblanc 121K Feb 23 13:35 builtin-check.o
-rw-rw-r--. 1 rleblanc rleblanc 4.2K Feb 23 13:35 .builtin-check.o.cmd
-rw-r-----. 1 rleblanc rleblanc  829 Dec 14 12:47 builtin.h
drwxr-x---. 2 rleblanc rleblanc   34 Dec 14 12:47 Documentation
-rw-r-----. 1 rleblanc rleblanc 8.6K Dec 14 12:47 elf.c
-rw-r-----. 1 rleblanc rleblanc 2.3K Dec 14 12:47 elf.h
-rw-rw-r--. 1 rleblanc rleblanc  49K Feb 23 13:35 elf.o
-rw-rw-r--. 1 rleblanc rleblanc 4.3K Feb 23 13:35 .elf.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 163K Feb 23 13:35 exec-cmd.o
-rw-rw-r--. 1 rleblanc rleblanc 3.4K Feb 23 13:35 .exec-cmd.o.cmd
-rwxrwxr-x. 1 rleblanc rleblanc  14K Feb 23 13:34 fixdep
-rw-rw-r--. 1 rleblanc rleblanc 4.9K Feb 23 13:34 fixdep-in.o
-rw-rw-r--. 1 rleblanc rleblanc  156 Feb 23 13:34 .fixdep-in.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 4.9K Feb 23 13:34 fixdep.o
-rw-rw-r--. 1 rleblanc rleblanc 2.3K Feb 23 13:34 .fixdep.o.cmd
-rw-r-----. 1 rleblanc rleblanc   43 Dec 14 12:47 .gitignore
-rw-rw-r--. 1 rleblanc rleblanc 201K Feb 23 13:35 help.o
-rw-rw-r--. 1 rleblanc rleblanc 3.3K Feb 23 13:35 .help.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 5.8K Feb 23 13:34 libstring.o
-rw-rw-r--. 1 rleblanc rleblanc 2.8K Feb 23 13:34 .libstring.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 728K Feb 23 13:35 libsubcmd.a
-rw-rw-r--. 1 rleblanc rleblanc 727K Feb 23 13:35 libsubcmd-in.o
-rw-rw-r--. 1 rleblanc rleblanc  446 Feb 23 13:35 .libsubcmd-in.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 2.4K Feb 23 13:27 Makefile
-rwxrwxr-x. 1 rleblanc rleblanc 431K Feb 23 13:35 objtool
-rw-r-----. 1 rleblanc rleblanc 3.0K Dec 14 12:47 objtool.c
-rw-rw-r--. 1 rleblanc rleblanc 286K Feb 23 13:35 objtool-in.o
-rw-rw-r--. 1 rleblanc rleblanc  449 Feb 23 13:35 .objtool-in.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc  16K Feb 23 13:35 objtool.o
-rw-rw-r--. 1 rleblanc rleblanc 2.4K Feb 23 13:35 .objtool.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 152K Feb 23 13:35 pager.o
-rw-rw-r--. 1 rleblanc rleblanc 3.3K Feb 23 13:35 .pager.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 198K Feb 23 13:35 parse-options.o
-rw-rw-r--. 1 rleblanc rleblanc 3.2K Feb 23 13:35 .parse-options.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 181K Feb 23 13:35 run-command.o
-rw-rw-r--. 1 rleblanc rleblanc 4.0K Feb 23 13:35 .run-command.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 112K Feb 23 13:35 sigchain.o
-rw-rw-r--. 1 rleblanc rleblanc 2.6K Feb 23 13:35 .sigchain.o.cmd
-rw-r-----. 1 rleblanc rleblanc 4.6K Dec 14 12:47 special.c
-rw-r-----. 1 rleblanc rleblanc 1.2K Dec 14 12:47 special.h
-rw-rw-r--. 1 rleblanc rleblanc  26K Feb 23 13:35 special.o
-rw-rw-r--. 1 rleblanc rleblanc 4.0K Feb 23 13:35 .special.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc 6.7K Feb 23 13:34 str_error_r.o
-rw-rw-r--. 1 rleblanc rleblanc 2.5K Feb 23 13:34 .str_error_r.o.cmd
-rw-rw-r--. 1 rleblanc rleblanc  18K Feb 23 13:34 subcmd-config.o
-rw-rw-r--. 1 rleblanc rleblanc 1.3K Feb 23 13:34 .subcmd-config.o.cmd
-rw-r-----. 1 rleblanc rleblanc 1.6K Dec 14 12:47 warn.h
$ cat tools/objtool/.fixdep.o.cmd
cmd_/home/rleblanc/linux/tools/objtool/fixdep.o := gcc -Wp,-MD,/home/rleblanc/linux/tools/objtool/.fixdep.o.d -Wp,-MT,/home/rleblanc/linux/tools/objtool/fixdep.o  -D"BUILD_STR(s)=\#s"   -c -o /home/rleblanc/linux/tools
/objtool/fixdep.o fixdep.c

source_/home/rleblanc/linux/tools/objtool/fixdep.o := fixdep.c

deps_/home/rleblanc/linux/tools/objtool/fixdep.o := \                                                                                                                                                                     
  /usr/include/stdc-predef.h \
  /usr/include/sys/types.h \
  /usr/include/features.h \                                   
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \                     
  /usr/include/gnu/stubs.h \  
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/time.h \         
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h \
  /usr/include/endian.h \      
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \ 
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \                              
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \    
  /usr/include/sys/sysmacros.h \   
  /usr/include/bits/pthreadtypes.h \
  /usr/include/sys/stat.h \   
  /usr/include/bits/stat.h \  
  /usr/include/sys/mman.h \ 
  /usr/include/bits/mman.h \    
  /usr/include/unistd.h \           
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \   
  /usr/include/fcntl.h \ 
  /usr/include/bits/fcntl.h \    
  /usr/include/bits/fcntl-linux.h \ 
  /usr/include/string.h \       
  /usr/include/xlocale.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \ 
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/stdio.h \ 
  /usr/include/libio.h \         
  /usr/include/_G_config.h \      
  /usr/include/wchar.h \ 
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h \
  /usr/include/limits.h \                                  
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \  
  /usr/include/linux/limits.h \                            
  /usr/include/bits/posix2_lim.h \                            
                         
/home/rleblanc/linux/tools/objtool/fixdep.o: $(deps_/home/rleblanc/linux/tools/objtool/fixdep.o)
                                 
$(deps_/home/rleblanc/linux/tools/objtool/fixdep.o):
```

**Comment by jrosdahl** [comment]
> $ ccache --version
> ccache version 3.2.7
> [...]
> cc1: error: to generate dependencies you must specify either -M or -MM
> mv: cannot stat ‘/home/rleblanc/linux/tools/objtool/.fixdep.o.tmp’: No such file or directory

@rldleblanc: Thanks! However, that's another bug: #129. It's fixed in ccache 3.2.9 and 3.3.2, so please try a newer ccache version and see if it fixes your problem.

@spstarr: I'm still interested in the content of `tools/objtool/.fixdep.o.cmd` with and without ccache. :)

**Comment by Chunyu-Hu** [comment]
Without ccache:
[root@dhcp-12-107 linux]# cat tools/objtool/.fixdep.o.cmd
cmd_/home/chuhu/Git/linux/tools/objtool/fixdep.o := gcc -Wp,-MD,/home/chuhu/Git/linux/tools/objtool/.fixdep.o.d -Wp,-MT,/home/chuhu/Git/linux/tools/objtool/fixdep.o  -D"BUILD_STR(s)=\#s"   -c -o /home/chuhu/Git/linux/tools/objtool/fixdep.o fixdep.c

source_/home/chuhu/Git/linux/tools/objtool/fixdep.o := fixdep.c

deps_/home/chuhu/Git/linux/tools/objtool/fixdep.o := \
  /usr/include/stdc-predef.h \
  /usr/include/sys/types.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/time.h \
  /home/chuhu/opt/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stddef.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/sys/mman.h \
  /usr/include/bits/mman.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /home/chuhu/opt/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /home/chuhu/opt/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include-fixed/limits.h \
  /home/chuhu/opt/gcc-6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/bits/posix2_lim.h \

/home/chuhu/Git/linux/tools/objtool/fixdep.o: $(deps_/home/chuhu/Git/linux/tools/objtool/fixdep.o)

$(deps_/home/chuhu/Git/linux/tools/objtool/fixdep.o):

**Comment by jrosdahl** [comment]
@Chunyu-Hu: Thanks, but that doesn't provide any new information. What I still would like to know is what `tools/objtool/.fixdep.o.cmd` looks like when ccache is used and you get an error like this:

```[...]/BUILD/kernel-4.10.0_rc6+/tools/objtool/.fixdep.o.cmd:3: *** empty variable name.  Stop.```

**Comment by spstarr** [comment]
@jrosdahl Still happens, ccache here is my .fixdep.o.cmd file *WITH* ccache enabled

`$ cat with-ccache-fixdep.o.cmd.txt 
cmd_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := gcc -Wp,-MD,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/.fixdep.o.d -Wp,-MT,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o  -D"BUILD_STR(s)=\#s"   -c -o /home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o fixdep.c

  /home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o \
source_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := fixdep.c

deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := \
  /usr/include/stdc-predef.h \
  /usr/include/sys/types.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/time.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/stddef.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/sys/mman.h \
  /usr/include/bits/mman.h \
  /usr/include/bits/mman-linux.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/limits.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/bits/posix2_lim.h \

/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o: $(deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o)

$(deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o):
`
                                                                                                                                                                      `

**Comment by spstarr** [comment]
@jrosdahl here is my .fixdep.o.cmd file *without* ccache enabled from 4.12-rc2 (tag from Linus)

[spstarr@segfault kernel-4.12.0_rc2]$ cat tools/objtool/.fixdep.o.cmd
cmd_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := gcc -Wp,-MD,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/.fixdep.o.d -Wp,-MT,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o  -D"BUILD_STR(s)=\#s"   -c -o /home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o fixdep.c

source_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := fixdep.c

deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := \
  /usr/include/stdc-predef.h \
  /usr/include/sys/types.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/time.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/stddef.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/sys/mman.h \
  /usr/include/bits/mman.h \
  /usr/include/bits/mman-linux.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/limits.h \
  /usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/bits/posix2_lim.h \

/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o: $(deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o)

$(deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o):

**Comment by spstarr** [comment]
The difference appears to be

`--- a   2017-05-24 01:55:02.917036565 -0400
+++ b   2017-05-24 01:55:10.877177171 -0400
@@ -1,6 +1,5 @@
 cmd_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := gcc -Wp,-MD,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/.fixdep.o.d -Wp,-MT,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o -D"BUILD_STR(s)=#s" -c -o /home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o fixdep.c
 
-/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o 
 source_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := fixdep.c
 
 deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := 
`

**Comment by spstarr** [comment]
@jrosdahl here is the differences

[spstarr@segfault ~]$ diff -Nrup without-ccache.fixdep.o.cmd ccache-enabled-fixdep.o.cmd 
```
--- without-ccache.fixdep.o.cmd 2017-05-24 06:01:13.158066224 -0400
+++ ccache-enabled-fixdep.o.cmd 2017-05-24 06:11:53.418066224 -0400
@@ -1,5 +1,6 @@
 cmd_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := gcc -Wp,-MD,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/.fixdep.o.d -Wp,-MT,/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o  -D"BUILD_STR(s)=\#s"   -c -o /home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o fixdep.c
 
+  /home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o \
 source_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := fixdep.c
 
 deps_/home/spstarr/rpmbuild/BUILD/kernel-4.12.0_rc2/tools/objtool/fixdep.o := \

```

**Comment by spstarr** [comment]
@jrosdahl Any update on this?

**Comment by spstarr** [comment]
So, I don't know what fixed this but i decided to nuke my whole git repo and now ccache works(?)

**Comment by jrosdahl** [comment]
> @jrosdahl here is the differences

Thanks! Very peculiar.

> @jrosdahl Any update on this?

Unfortunately no. I have not managed to reproduce the problem, and I don't get any brilliant ideas from the diff you posted. The only way forward I see is to do some debugging in an environment where the problem shows up.

**Comment by jrosdahl** [comment]
> So, I don't know what fixed this but i decided to nuke my whole git repo and now ccache works(?)

I'm closing this issue now. Will be reopened again if/when you or somebody else see the problem again.

**Comment by jrosdahl** [comment]
> i have the problem.

And I would love to have the problem so that I could debug the issue...

> the 'fix' of just simply not using the orc unwinder does still work

You lost me there. Where has that fix been mentioned before? And what do you mean with "not using the orc unwinder"?

**Comment by prototype99** [comment]
CONFIG_HAVE_STACK_VALIDATION is what causes the error according to earlier comments and is a requirement of the orc unwinder, so if you change the unwinder, that does solve it, although that is a workaround more than a solution. i can't think what the option is called, but you find it in the kernel hacking section
