### ISSUE TITLE
Precompiled header causes wrong cache misses on rebuild

### ISSUE THREAD

**Issue by orgads** [ccache/ccache#184]
My project uses a precompiled header. I configured `sloppiness = time_macros`.

If I rebuild a single file, I get a direct hit. If I rebuild the entire project (regenerating the precompiled header), everything is preprocessed for matching.

A few observations:
* The function [is_precompiled_header](https://github.com/ccache/ccache/blob/81d295156d2412875e8dc0a62f47bb972ed5973f/ccache.c#L2114) doesn't work well for gcc. gcc creates 2 files: `<path>/header.h.gch/c` and `<path>/header.h.gch/c++`. The function matches by extension, which is absent in these files.
* I've noticed in the log: `Include file ./..\build\obj\precompiled.h.gch/c++ too new`. Full log is [here](https://gist.github.com/orgads/2e205468000a72d43d96ef518941e087).

**Comment by jrosdahl** [comment]
> The function is_precompiled_header doesn't work well for gcc. gcc creates 2 files: <path>/header.h.gch/c and <path>/header.h.gch/c++. The function matches by extension, which is absent in these files.

Hmm, the [pch test suite](https://github.com/ccache/ccache/blob/master/test/suites/pch.bash) is full of tests that generate files named `.h.gch`, so no directory in sight there. Which compiler and system are you using?

**Comment by jrosdahl** [comment]
Also, please tell how to reproduce your problem if possible.

**Comment by orgads** [comment]
This is a qmake/mingw project.

The most basic sample is:

header.h:
```
#define SOME_VAR 42
```

main.cpp:
```
#include "header.h"

int main() { return 0; }
```

project.pro:
```
CONFIG = debug precompile_header
PRECOMPILED_HEADER = header.h
SOURCES += main.cpp
```

Then run `qmake`.

The relevant parts in the Makefile look like this (stripped):
```
CC            = gcc
CXX           = g++
header.h.gch/c: header.h
        @test -d header.h.gch || mkdir -p header.h.gch
        $(CC) -x c-header -c -o header.h.gch/c header.h

header.h.gch/c++: header.h
        @test -d header.h.gch || mkdir -p header.h.gch
        $(CXX) -x c++-header -c -o header.h.gch/c++ header.h

####### Compile

main.o: main.cpp header.h \
                header.h.gch/c++
        $(CXX) -c -include header.h -o main.o main.cpp
```

**Comment by jrosdahl** [comment]
I see. From https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html:

> _“If you need to precompile the same header file for different languages, targets, or compiler options, you can instead make a directory named like all.h.gch, and put each precompiled header in the directory, perhaps using -o. It doesn’t matter what you call the files in the directory; every precompiled header in the directory is considered. The first precompiled header encountered in the directory that is valid for this compilation is used; they’re searched in no particular order.”_

That shouldn't be a problem for ccache since the output then is specified with `-o`. `is_precompiled_header` is only used to know if an include file mentioned in the preprocessed output should be hashed separately. So the bug I see is that you risk getting _too many_ (i.e. false positive) hits if `header.h.gch/c++` is updated since it won't be part of the hash when compiling `main.o`.

> I've noticed in the log: Include file ./..\build\obj\precompiled.h.gch/c++ too new. Full log is here.

I suspect that this is your main problem. From [_Performance_ in the ccache manual](http://ccache.samba.org/manual/latest.html#_performance):

> _“A modification time of one of the include files is too new (created the same second as the compilation is being done). This check is made to avoid a race condition. To fix this, create the include file earlier in the build process, if possible, or set sloppiness to include_file_mtime if you are willing to take the risk. (The race condition consists of these events: the preprocessor is run; an include file is modified by someone; the new include file is hashed by ccache; the real compiler is run on the preprocessor’s output, which contains data from the old header file; the wrong object file is stored in the cache.)”_

That is, try setting `include_file_mtime` sloppiness as well and see if that changes anything.

**Comment by jrosdahl** [comment]
> So the bug I see is that you risk getting too many (i.e. false positive) hits if header.h.gch/c++ is updated since it won't be part of the hash when compiling main.o.

Fixed in a2280c55ce5575bce48b3699b075f0c6b074bb6a.

**Comment by jrosdahl** [comment]
@orgads: Closing this now, please comment if you think that it should remain open.

**Comment by alecazam** [comment]
We are having a terrible time using ccache and clang precompiled headers.  Had to disable ccache.  Constantly getting complaints about mtime change from the time the pch was built.   The time of the .h is older than the .pch (by 1s), so something inside the pch thinks it no longer matches mtime with the .h file.

So something is still broken here, and the guidance doesn't seem to help.  I just disabled ccache, so will report back if the previously bad behavior is gone.   We use clang on Linux, macOS, iOS, Android, Win, and consoles.  And they were all failing with various version of clang 12 to 17.

Also tried include_file_mtime here
CCACHE_ARGS := sloppiness=pch_defines,time_macros

And this added to compiles
PRECOMPILED_CXXFLAGS += -Xclang -fno-pch-timestamp

**Comment by jrosdahl** [comment]
@alecazam: This issue was about a specific problem with GCC which is already solved. Since you're talking about another issue with another compiler, please open a new issue or discussion instead of commenting on a 6 years old closed issue.
